### ISSUE TITLE
Wrong command data when re-enable validator.

### ISSUE THREAD

**Issue by nefer05** [ubombi/cashcode_ccnet#3]
Call 
self.cmd('ENABLE BILL TYPES').request(billsEnable)
multiple time and you get 
34FFFFFF000000
3434FFFFFF000000
343434FFFFFF000000
34343434FFFFFF000000
as result.

**Comment by alex-eri** [comment]
this is because  `def start(self,  billsEnable=[0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF])`


`billsEnable` is modified each call.
